[package]
name = "razi"
version = "0.1.0"
authors = ["Vamist <Vamist@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.8.6"
toml = "0.5.6"
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.56"
isahc = "0.9.5"
chrono = "0.4.13"


[profile.release]
opt-level = 3
lto="fat"
codegen-units = 1