[discord]
release_token = ""
test_token = ""
prefixes = [".", "~"]
allowed_channels = []
owners = []
release_run = false  

[[kag_server]]
names = ["tc"]
ip = "85.10.195.233"
port = "50309"
minimap = true

[[kag_server]]
names = ["mc", "3d", "goldenguy"]
ip = "85.10.195.233"
port = "50303"
minimap = true

[[kag_server]]
names = ["wizard", "ww"]
ip = "85.10.195.233"
port = "50301"
minimap = true

[[kag_server]]
names = ["lwb", "classes"]
ip = "85.10.195.233"
port = "50310"
minimap = true

[[kag_server]]
names = ["volley", "vb", "volleyball"]
ip = "85.10.195.233"
port = "50302"
minimap = true
